### PR TITLE
Update to linked-hash-map 0.5 and heapsize 0.4

### PR DESCRIPTION
**Pull request by debris**
Please publish new version to crates.io

### CODE REVIEW

**Comment by FlashCat** [comment]
Thanks for the pull request, and welcome! The contain-rs team is excited to review your changes, and you should hear from @reem (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way Github handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

**Comment by kpcyrd** [comment]
@reem Any updates on this one? :)

**Review by Gankra — APPROVED** [review]
thanks!

**Comment by Gankra** [comment]
(I'll push the update later tonight when I'm at the machine I have setup for this)

**Comment by debris** [comment]
haha, one year later 🎉

**Comment by kpcyrd** [comment]
@Gankro forgot to push? :)

**Comment by Gankra** [comment]
sorry, done now :)

**Pull request merged**
