### PR TITLE
remove quotes from `extern crate`

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @huonw

(I've picked a reviewer for you, use r? to override)

**Comment by Gankra** [comment]
Needs update to handle new linked_hash_map indexing.

**Comment by apasel422** [comment]
I think it'll work without any changes once a new version of linked-hash-map is published.

**Comment by Gankra** [comment]
Oh whoops, thought I published that one.

**Pull request merged**
