### PR TITLE
Assorted cleanup

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @cgaebel

(I've picked a reviewer for you, use r? to override)

**Comment by Gankra** [comment]
@FlashCat r+

**Comment by FlashCat** [comment]
:pushpin: Commit e75b1fa has been approved by `Gankro`

**Comment by FlashCat** [comment]
:hourglass: Testing commit e75b1fa with merge 260424a...

**Comment by FlashCat** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/contain-rs/lru-cache/builds/55031556)

**Comment by FlashCat** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/contain-rs/lru-cache/builds/55031558)

**Pull request merged**
